; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc1-n8r8
monitor_filters = esp32_exception_decoder
framework = arduino
monitor_speed = 115200
upload_port = COM5
lib_deps = 
	symlink://../..
	symlink://../../profile_catalog
build_src_filter = 
	+<*.cpp>
board_build.partitions = partitions_8M.csv
build_flags = 
	-std=gnu++17
	-DESPNOW_LINK_PMK='"A7F3C91D4E2B86A0"'
	-I../../profile_catalog/include
